/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/brain.glb -o src/components/BrainModel.tsx
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";

type GLTFResult = GLTF & {
  nodes: {
    Anterior_communicating_artery: THREE.Mesh;
    Basilar_venous_plexus: THREE.Mesh;
    Cavernous_sinusr: THREE.Mesh;
    Cavernous_sinusl: THREE.Mesh;
    Anterior_cerebral_arteryl: THREE.Mesh;
    Anterior_cerebral_arteryr: THREE.Mesh;
    Anterior_inferior_cerebellar_arteryl: THREE.Mesh;
    Anterior_inferior_cerebellar_arteryr: THREE.Mesh;
    Anterior_intercavernous_sinus: THREE.Mesh;
    Anterior_spinal_arteryl: THREE.Mesh;
    Anterior_spinal_arteryr: THREE.Mesh;
    Basilar_artery: THREE.Mesh;
    Callosomarginal_arteryl: THREE.Mesh;
    Callosomarginal_arteryr: THREE.Mesh;
    Distal_lateral_striate_branchesl: THREE.Mesh;
    Distal_lateral_striate_branchesr: THREE.Mesh;
    Frontal_branches_of_callosomarginal_arteryl: THREE.Mesh;
    Frontal_branches_of_callosomarginal_arteryr: THREE.Mesh;
    Inferior_petrosal_sinusl: THREE.Mesh;
    Inferior_petrosal_sinusr: THREE.Mesh;
    Inferior_sagittal_sinus: THREE.Mesh;
    ["Insular_branches_of_middle_cerebral_artery_(M2)r"]: THREE.Mesh;
    ["Insular_branches_of_middle_cerebral_artery_(M2-segment)l"]: THREE.Mesh;
    Internal_carotid_arteryl: THREE.Mesh;
    Internal_carotid_arteryr: THREE.Mesh;
    Lateral_pontine_branches_of_basilar_arteryl: THREE.Mesh;
    Lateral_pontine_branches_of_basilar_arteryr: THREE.Mesh;
    Medial_pontine_branches_of_basilar_arteryl: THREE.Mesh;
    Medial_pontine_branches_of_basilar_arteryr: THREE.Mesh;
    ["Middle_cerebral_artery_(M1-segment)l"]: THREE.Mesh;
    ["Middle_cerebral_artery_(M1-segment)r"]: THREE.Mesh;
    ["Middle_cerebral_artery_(M3_segment)l"]: THREE.Mesh;
    ["Middle_cerebral_artery_(M3-segment)r"]: THREE.Mesh;
    Occipital_sinus: THREE.Mesh;
    Ophthalmic_arteryl: THREE.Mesh;
    Ophthalmic_arteryr: THREE.Mesh;
    Orbitofrontal_branches_of_anterior_cerebral_arteryl: THREE.Mesh;
    Orbitofrontal_branches_of_anterior_cerebral_arteryr: THREE.Mesh;
    Parietal_branches_of_middle_cerebral_arteryl: THREE.Mesh;
    Parietal_branches_of_middle_cerebral_arteryr: THREE.Mesh;
    Pericallosal_arteryl: THREE.Mesh;
    Pericallosal_arteryr: THREE.Mesh;
    Posterior_cerebral_arteryl: THREE.Mesh;
    Posterior_cerebral_arteryr: THREE.Mesh;
    Posterior_communicating_arteryl: THREE.Mesh;
    Posterior_communicating_arteryr: THREE.Mesh;
    Posterior_inferior_cerebellar_arteryl: THREE.Mesh;
    Posterior_inferior_cerebellar_arteryr: THREE.Mesh;
    Posterior_intercavernous_sinus: THREE.Mesh;
    Proximal_lateral_striate_branchesl: THREE.Mesh;
    Proximal_lateral_striate_branchesr: THREE.Mesh;
    Sigmoid_sinusl: THREE.Mesh;
    Sigmoid_sinusr: THREE.Mesh;
    Straight_sinus: THREE.Mesh;
    Superior_cerebellar_arteryl: THREE.Mesh;
    Superior_cerebellar_arteryr: THREE.Mesh;
    Superior_petrosal_sinusl: THREE.Mesh;
    Superior_petrosal_sinusr: THREE.Mesh;
    Superior_sagittal_sinus: THREE.Mesh;
    Temporal_branches_of_middle_cerebral_arteryl: THREE.Mesh;
    Temporal_branches_of_middle_cerebral_arteryr: THREE.Mesh;
    Transverse_sinusl: THREE.Mesh;
    Transverse_sinusr: THREE.Mesh;
    Vertebral_arteryl: THREE.Mesh;
    Vertebral_arteryr: THREE.Mesh;
    Tentorium_cerebellir: THREE.Mesh;
    Falx_cerebri: THREE.Mesh;
    Choroid_plexusr: THREE.Mesh;
    Choroid_plexusl: THREE.Mesh;
    Temporal_pole001: THREE.Mesh;
    Temporal_pole001_1: THREE.Mesh;
    Occipital_pole001: THREE.Mesh;
    Occipital_pole001_1: THREE.Mesh;
    Central_sulcus001: THREE.Mesh;
    Central_sulcus001_1: THREE.Mesh;
    ["Parieto-occipital_sulcus001"]: THREE.Mesh;
    ["Parieto-occipital_sulcus001_1"]: THREE.Mesh;
    Subparietal_sulcus001: THREE.Mesh;
    Subparietal_sulcus001_1: THREE.Mesh;
    ["Cingulate_sulcus_(Marginal_part*)001"]: THREE.Mesh;
    ["Cingulate_sulcus_(Marginal_part*)001_1"]: THREE.Mesh;
    Circular_sulcus_of_insula001: THREE.Mesh;
    Circular_sulcus_of_insula001_1: THREE.Mesh;
    Collateral_sulcus001: THREE.Mesh;
    Collateral_sulcus001_1: THREE.Mesh;
    ["Anterior_occipital_sulcus*001"]: THREE.Mesh;
    ["Anterior_occipital_sulcus*001_1"]: THREE.Mesh;
    Opercular_part_of_inferior_frontal_gyrus001: THREE.Mesh;
    Opercular_part_of_inferior_frontal_gyrus001_1: THREE.Mesh;
    Orbital_part_of__inferior_frontal_gyrus001: THREE.Mesh;
    Orbital_part_of__inferior_frontal_gyrus001_1: THREE.Mesh;
    Triangular_part_of_inferior_frontal_gyrus001: THREE.Mesh;
    Triangular_part_of_inferior_frontal_gyrus001_1: THREE.Mesh;
    ["Orbital_gyri_(Frontomarginal_gyrus_and_sulcus*)001"]: THREE.Mesh;
    ["Orbital_gyri_(Frontomarginal_gyrus_and_sulcus*)001_1"]: THREE.Mesh;
    ["Paracentral_gyrus_and_sulcus*001"]: THREE.Mesh;
    ["Paracentral_gyrus_and_sulcus*001_1"]: THREE.Mesh;
    ["Transverse_frontopolar_gyrus_and_sulcus*001"]: THREE.Mesh;
    ["Transverse_frontopolar_gyrus_and_sulcus*001_1"]: THREE.Mesh;
    ["Straight_gyrus_(Gyrus_rectus)001"]: THREE.Mesh;
    ["Straight_gyrus_(Gyrus_rectus)001_1"]: THREE.Mesh;
    ["Lat_Fis-ant-Vertical001"]: THREE.Mesh;
    ["Lat_Fis-ant-Vertical001_1"]: THREE.Mesh;
    Inferior_frontal_sulcus001: THREE.Mesh;
    Inferior_frontal_sulcus001_1: THREE.Mesh;
    Middle_frontal_gyrus001: THREE.Mesh;
    Middle_frontal_gyrus001_1: THREE.Mesh;
    Orbital_gyri001: THREE.Mesh;
    Orbital_gyri001_1: THREE.Mesh;
    Precentral_gyrus001: THREE.Mesh;
    Precentral_gyrus001_1: THREE.Mesh;
    Superior_frontal_gyrus001: THREE.Mesh;
    Superior_frontal_gyrus001_1: THREE.Mesh;
    Superior_frontal_sulcus001: THREE.Mesh;
    Superior_frontal_sulcus001_1: THREE.Mesh;
    Paracentral_sulcus001: THREE.Mesh;
    Paracentral_sulcus001_1: THREE.Mesh;
    ["Orbital_sulci_(H-shaped_orbital_sulci*)001"]: THREE.Mesh;
    ["Orbital_sulci_(H-shaped_orbital_sulci*)001_1"]: THREE.Mesh;
    ["Orbital_sulci_(Lateral_Orbital_sulcus*)001"]: THREE.Mesh;
    ["Orbital_sulci_(Lateral_Orbital_sulcus*)001_1"]: THREE.Mesh;
    Olfactory_sulcus001: THREE.Mesh;
    Olfactory_sulcus001_1: THREE.Mesh;
    ["Precentral_sulcus_(inferior_part)*001"]: THREE.Mesh;
    ["Precentral_sulcus_(inferior_part)*001_1"]: THREE.Mesh;
    ["Precentral_sulcus_(Superior_part)*001"]: THREE.Mesh;
    ["Precentral_sulcus_(Superior_part)*001_1"]: THREE.Mesh;
    Angular_gyrus001: THREE.Mesh;
    Angular_gyrus001_1: THREE.Mesh;
    Supramarginal_gyrus001: THREE.Mesh;
    Supramarginal_gyrus001_1: THREE.Mesh;
    Postcentral_gyrus001: THREE.Mesh;
    Postcentral_gyrus001_1: THREE.Mesh;
    Postcentral_sulcus001: THREE.Mesh;
    Postcentral_sulcus001_1: THREE.Mesh;
    Precuneus001: THREE.Mesh;
    Precuneus001_1: THREE.Mesh;
    Superior_parietal_lobule001: THREE.Mesh;
    Superior_parietal_lobule001_1: THREE.Mesh;
    Intraparietal_sulcus001: THREE.Mesh;
    Intraparietal_sulcus001_1: THREE.Mesh;
    ["Inferior_occipital_gyrus_and_sulcus*001"]: THREE.Mesh;
    ["Inferior_occipital_gyrus_and_sulcus*001_1"]: THREE.Mesh;
    Lingual_gyrus001: THREE.Mesh;
    Lingual_gyrus001_1: THREE.Mesh;
    ["Lateral_occipital_gyrus_(Middle_occipital_gyrus*)001"]: THREE.Mesh;
    ["Lateral_occipital_gyrus_(Middle_occipital_gyrus*)001_1"]: THREE.Mesh;
    Calcarine_sulcus001: THREE.Mesh;
    Calcarine_sulcus001_1: THREE.Mesh;
    Cuneus001: THREE.Mesh;
    Cuneus001_1: THREE.Mesh;
    Superior_occipital_gyri001: THREE.Mesh;
    Superior_occipital_gyri001_1: THREE.Mesh;
    Lunate_sulcus001: THREE.Mesh;
    Lunate_sulcus001_1: THREE.Mesh;
    Transverse_occipital_sulcus001: THREE.Mesh;
    Transverse_occipital_sulcus001_1: THREE.Mesh;
    Transverse_temporal_gyri001: THREE.Mesh;
    Transverse_temporal_gyri001_1: THREE.Mesh;
    Temporal_plane001: THREE.Mesh;
    Temporal_plane001_1: THREE.Mesh;
    ["Superior_temporal_gyrus_(Lateral_part)001"]: THREE.Mesh;
    ["Superior_temporal_gyrus_(Lateral_part)001_1"]: THREE.Mesh;
    Lateral_occipitotemporal_gyrus001: THREE.Mesh;
    Lateral_occipitotemporal_gyrus001_1: THREE.Mesh;
    ["Medial_occipitotemporal_gyrus_(Parahippocampal*)001"]: THREE.Mesh;
    ["Medial_occipitotemporal_gyrus_(Parahippocampal*)001_1"]: THREE.Mesh;
    Inferior_temporal_sulcus001: THREE.Mesh;
    Inferior_temporal_sulcus001_1: THREE.Mesh;
    Inferior_temporal_gyrus001: THREE.Mesh;
    Inferior_temporal_gyrus001_1: THREE.Mesh;
    Middle_temporal_gyrus001: THREE.Mesh;
    Middle_temporal_gyrus001_1: THREE.Mesh;
    Superior_temporal_sulcus001: THREE.Mesh;
    Superior_temporal_sulcus001_1: THREE.Mesh;
    ["Occipitotemporal_sulcus_(Lateral_part*)001"]: THREE.Mesh;
    ["Occipitotemporal_sulcus_(Lateral_part*)001_1"]: THREE.Mesh;
    ["Insula_(Subcentral_gyrus_and_ant_and_post_sulci*)001"]: THREE.Mesh;
    ["Insula_(Subcentral_gyrus_and_ant_and_post_sulci*)001_1"]: THREE.Mesh;
    ["Cingulate_gyrus_and_sulcus_(Middle_anterior_part)001"]: THREE.Mesh;
    ["Cingulate_gyrus_and_sulcus_(Middle_anterior_part)001_1"]: THREE.Mesh;
    ["Cingulate_gyrus_and_sulcus_(Middle_posterior_part)001"]: THREE.Mesh;
    ["Cingulate_gyrus_and_sulcus_(Middle_posterior_part)001_1"]: THREE.Mesh;
    ["Cingulate_gyrus_and_sulcus_(Posterior_dorsal_part)001"]: THREE.Mesh;
    ["Cingulate_gyrus_and_sulcus_(Posterior_dorsal_part)001_1"]: THREE.Mesh;
    ["Cingulate_gyrus_(Posteroventral_part*)001"]: THREE.Mesh;
    ["Cingulate_gyrus_(Posteroventral_part*)001_1"]: THREE.Mesh;
    Hippocampusr: THREE.Mesh;
    Hippocampusl: THREE.Mesh;
    Septal_nuclei: THREE.Mesh;
    Caudate_nucleusr: THREE.Mesh;
    Caudate_nucleusl: THREE.Mesh;
    Putamenr: THREE.Mesh;
    Putamenl: THREE.Mesh;
    Corpus_callosum: THREE.Mesh;
    Anterior_commissure: THREE.Mesh;
    Hippocampal_commissure: THREE.Mesh;
    Fornixr: THREE.Mesh;
    Fornixl: THREE.Mesh;
    Stria_terminalisr: THREE.Mesh;
    Stria_terminalisl: THREE.Mesh;
    White_matter_of_telencephalonl: THREE.Mesh;
    Lateral_ventricler: THREE.Mesh;
    Lateral_ventriclel: THREE.Mesh;
    Septum_pellucidum: THREE.Mesh;
    ["Lat_Fis-ant-Horizont001"]: THREE.Mesh;
    ["Lat_Fis-ant-Horizont001_1"]: THREE.Mesh;
    ["Lat_Fis-post001"]: THREE.Mesh;
    ["Lat_Fis-post001_1"]: THREE.Mesh;
    _Posterior_transverse_collateral_sulcus001: THREE.Mesh;
    _Posterior_transverse_collateral_sulcus001_1: THREE.Mesh;
    ["Sulcus_interm_prim-Jensen001"]: THREE.Mesh;
    ["Sulcus_interm_prim-Jensen001_1"]: THREE.Mesh;
    Habenula: THREE.Mesh;
    Optic_tractr: THREE.Mesh;
    Optic_tractl: THREE.Mesh;
    Stria_medullaris_thalamir: THREE.Mesh;
    Stria_medullaris_thalamil: THREE.Mesh;
    Posterior_commissure: THREE.Mesh;
    Third_ventricle: THREE.Mesh;
    Lateral_geniculate_bodyr: THREE.Mesh;
    Medial_geniculate_bodyr: THREE.Mesh;
    Mamillary_bodyl: THREE.Mesh;
    Mamillary_bodyr: THREE.Mesh;
    Optic_chiasmr: THREE.Mesh;
    Lateral_geniculate_bodyl: THREE.Mesh;
    Medial_geniculate_bodyl: THREE.Mesh;
    Optic_chiasml: THREE.Mesh;
    Base_of_peduncler: THREE.Mesh;
    Base_of_pedunclel: THREE.Mesh;
    Nucleus_of_oculomotor_nervel: THREE.Mesh;
    Nucleus_of_oculomotor_nerver: THREE.Mesh;
    Accessory_nucleus_of_oculomotor_nerver: THREE.Mesh;
    Accessory_nucleus_of_oculomotor_nervel: THREE.Mesh;
    Red_nucleusl: THREE.Mesh;
    Red_nucleusr: THREE.Mesh;
    Aqueduct_of_midbrain: THREE.Mesh;
    Superior_colliculusr: THREE.Mesh;
    Superior_colliculusl: THREE.Mesh;
    Inferior_colliculusr: THREE.Mesh;
    Inferior_colliculusl: THREE.Mesh;
    Midbrainr: THREE.Mesh;
    Interpeduncular_fossal: THREE.Mesh;
    Interpeduncular_fossar: THREE.Mesh;
    Midbrainl: THREE.Mesh;
    Vestibular_nucleil: THREE.Mesh;
    Vestibular_nucleir: THREE.Mesh;
    Nucleus_of_abducens_nervel: THREE.Mesh;
    Nucleus_of_abducens_nerver: THREE.Mesh;
    Motor_nucleus_of_facial_nervel: THREE.Mesh;
    Motor_nucleus_of_facial_nerver: THREE.Mesh;
    Superior_salivatory_nucleusl: THREE.Mesh;
    Superior_salivatory_nucleusr: THREE.Mesh;
    Ponsr: THREE.Mesh;
    Ponsl: THREE.Mesh;
    Fourth_ventricle: THREE.Mesh;
    Medulla_oblongatal: THREE.Mesh;
    Pyramid_of_medulla_oblongatal: THREE.Mesh;
    Oliver: THREE.Mesh;
    Olivel: THREE.Mesh;
    Pyramid_of_medulla_oblongatar: THREE.Mesh;
    Sensory_root_of_trigeminal_nerver: THREE.Mesh;
    Sensory_root_of_trigeminal_nervel: THREE.Mesh;
    Motor_root_of_trigeminal_nervel: THREE.Mesh;
    Motor_root_of_trigeminal_nerver: THREE.Mesh;
    Wing_of_central_lobulel: THREE.Mesh;
    Uvula_of_vermis: THREE.Mesh;
    Tuber_of_vermis: THREE.Mesh;
    Tonsil_of_cerebelluml: THREE.Mesh;
    Superior_semilunar_lobulel: THREE.Mesh;
    Superior_cerebellar_pedunclel: THREE.Mesh;
    Pyramis_of_vermis: THREE.Mesh;
    Posterior_quadrangular_lobulel: THREE.Mesh;
    Peduncle_of_flocculusl: THREE.Mesh;
    Nodule_of_vermis: THREE.Mesh;
    Lingula_of_cerebellum: THREE.Mesh;
    Inferior_semilunar_lobulel: THREE.Mesh;
    Gracile_lobulel: THREE.Mesh;
    Folium_of_vermis: THREE.Mesh;
    Flocculusl: THREE.Mesh;
    Declive: THREE.Mesh;
    Culmen: THREE.Mesh;
    Central_lobule: THREE.Mesh;
    Biventral_lobulel: THREE.Mesh;
    Anterior_quadrangular_lobulel: THREE.Mesh;
    Temporal_pole: THREE.Mesh;
    Temporal_pole_1: THREE.Mesh;
    Occipital_pole: THREE.Mesh;
    Occipital_pole_1: THREE.Mesh;
    Central_sulcus: THREE.Mesh;
    Central_sulcus_1: THREE.Mesh;
    ["Parieto-occipital_sulcus"]: THREE.Mesh;
    ["Parieto-occipital_sulcus_1"]: THREE.Mesh;
    Subparietal_sulcus: THREE.Mesh;
    Subparietal_sulcus_1: THREE.Mesh;
    ["Cingulate_sulcus_(Marginal_part*)"]: THREE.Mesh;
    ["Cingulate_sulcus_(Marginal_part*)_1"]: THREE.Mesh;
    Circular_sulcus_of_insula: THREE.Mesh;
    Circular_sulcus_of_insula_1: THREE.Mesh;
    Collateral_sulcus: THREE.Mesh;
    Collateral_sulcus_1: THREE.Mesh;
    ["Anterior_occipital_sulcus*"]: THREE.Mesh;
    ["Anterior_occipital_sulcus*_1"]: THREE.Mesh;
    Opercular_part_of_inferior_frontal_gyrus: THREE.Mesh;
    Opercular_part_of_inferior_frontal_gyrus_1: THREE.Mesh;
    Orbital_part_of__inferior_frontal_gyrus: THREE.Mesh;
    Orbital_part_of__inferior_frontal_gyrus_1: THREE.Mesh;
    Triangular_part_of_inferior_frontal_gyrus: THREE.Mesh;
    Triangular_part_of_inferior_frontal_gyrus_1: THREE.Mesh;
    ["Orbital_gyri_(Frontomarginal_gyrus_and_sulcus*)"]: THREE.Mesh;
    ["Orbital_gyri_(Frontomarginal_gyrus_and_sulcus*)_1"]: THREE.Mesh;
    ["Paracentral_gyrus_and_sulcus*"]: THREE.Mesh;
    ["Paracentral_gyrus_and_sulcus*_1"]: THREE.Mesh;
    ["Transverse_frontopolar_gyrus_and_sulcus*"]: THREE.Mesh;
    ["Transverse_frontopolar_gyrus_and_sulcus*_1"]: THREE.Mesh;
    ["Straight_gyrus_(Gyrus_rectus)"]: THREE.Mesh;
    ["Straight_gyrus_(Gyrus_rectus)_1"]: THREE.Mesh;
    ["Lat_Fis-ant-Vertical"]: THREE.Mesh;
    ["Lat_Fis-ant-Vertical_1"]: THREE.Mesh;
    Inferior_frontal_sulcus: THREE.Mesh;
    Inferior_frontal_sulcus_1: THREE.Mesh;
    Middle_frontal_gyrus: THREE.Mesh;
    Middle_frontal_gyrus_1: THREE.Mesh;
    Orbital_gyri: THREE.Mesh;
    Orbital_gyri_1: THREE.Mesh;
    Precentral_gyrus: THREE.Mesh;
    Precentral_gyrus_1: THREE.Mesh;
    Superior_frontal_gyrus: THREE.Mesh;
    Superior_frontal_gyrus_1: THREE.Mesh;
    Superior_frontal_sulcus: THREE.Mesh;
    Superior_frontal_sulcus_1: THREE.Mesh;
    Paracentral_sulcus: THREE.Mesh;
    Paracentral_sulcus_1: THREE.Mesh;
    ["Orbital_sulci_(H-shaped_orbital_sulci*)"]: THREE.Mesh;
    ["Orbital_sulci_(H-shaped_orbital_sulci*)_1"]: THREE.Mesh;
    ["Orbital_sulci_(Lateral_Orbital_sulcus*)"]: THREE.Mesh;
    ["Orbital_sulci_(Lateral_Orbital_sulcus*)_1"]: THREE.Mesh;
    Olfactory_sulcus: THREE.Mesh;
    Olfactory_sulcus_1: THREE.Mesh;
    ["Precentral_sulcus_(inferior_part)*"]: THREE.Mesh;
    ["Precentral_sulcus_(inferior_part)*_1"]: THREE.Mesh;
    ["Precentral_sulcus_(Superior_part)*"]: THREE.Mesh;
    ["Precentral_sulcus_(Superior_part)*_1"]: THREE.Mesh;
    Angular_gyrus: THREE.Mesh;
    Angular_gyrus_1: THREE.Mesh;
    Supramarginal_gyrus: THREE.Mesh;
    Supramarginal_gyrus_1: THREE.Mesh;
    Postcentral_gyrus: THREE.Mesh;
    Postcentral_gyrus_1: THREE.Mesh;
    Postcentral_sulcus: THREE.Mesh;
    Postcentral_sulcus_1: THREE.Mesh;
    Precuneus: THREE.Mesh;
    Precuneus_1: THREE.Mesh;
    Superior_parietal_lobule: THREE.Mesh;
    Superior_parietal_lobule_1: THREE.Mesh;
    Intraparietal_sulcus: THREE.Mesh;
    Intraparietal_sulcus_1: THREE.Mesh;
    ["Inferior_occipital_gyrus_and_sulcus*"]: THREE.Mesh;
    ["Inferior_occipital_gyrus_and_sulcus*_1"]: THREE.Mesh;
    Lingual_gyrus: THREE.Mesh;
    Lingual_gyrus_1: THREE.Mesh;
    ["Lateral_occipital_gyrus_(Middle_occipital_gyrus*)"]: THREE.Mesh;
    ["Lateral_occipital_gyrus_(Middle_occipital_gyrus*)_1"]: THREE.Mesh;
    Calcarine_sulcus: THREE.Mesh;
    Calcarine_sulcus_1: THREE.Mesh;
    Cuneus: THREE.Mesh;
    Cuneus_1: THREE.Mesh;
    Superior_occipital_gyri: THREE.Mesh;
    Superior_occipital_gyri_1: THREE.Mesh;
    Lunate_sulcus: THREE.Mesh;
    Lunate_sulcus_1: THREE.Mesh;
    Transverse_occipital_sulcus: THREE.Mesh;
    Transverse_occipital_sulcus_1: THREE.Mesh;
    Transverse_temporal_gyri: THREE.Mesh;
    Transverse_temporal_gyri_1: THREE.Mesh;
    Temporal_plane: THREE.Mesh;
    Temporal_plane_1: THREE.Mesh;
    ["Superior_temporal_gyrus_(Lateral_part)"]: THREE.Mesh;
    ["Superior_temporal_gyrus_(Lateral_part)_1"]: THREE.Mesh;
    Lateral_occipitotemporal_gyrus: THREE.Mesh;
    Lateral_occipitotemporal_gyrus_1: THREE.Mesh;
    ["Medial_occipitotemporal_gyrus_(Parahippocampal*)"]: THREE.Mesh;
    ["Medial_occipitotemporal_gyrus_(Parahippocampal*)_1"]: THREE.Mesh;
    Inferior_temporal_sulcus: THREE.Mesh;
    Inferior_temporal_sulcus_1: THREE.Mesh;
    Inferior_temporal_gyrus: THREE.Mesh;
    Inferior_temporal_gyrus_1: THREE.Mesh;
    Middle_temporal_gyrus: THREE.Mesh;
    Middle_temporal_gyrus_1: THREE.Mesh;
    Superior_temporal_sulcus: THREE.Mesh;
    Superior_temporal_sulcus_1: THREE.Mesh;
    ["Occipitotemporal_sulcus_(Lateral_part*)"]: THREE.Mesh;
    ["Occipitotemporal_sulcus_(Lateral_part*)_1"]: THREE.Mesh;
    ["Insula_(Subcentral_gyrus_and_ant_and_post_sulci*)"]: THREE.Mesh;
    ["Insula_(Subcentral_gyrus_and_ant_and_post_sulci*)_1"]: THREE.Mesh;
    ["Cingulate_gyrus_and_sulcus_(Middle_anterior_part)"]: THREE.Mesh;
    ["Cingulate_gyrus_and_sulcus_(Middle_anterior_part)_1"]: THREE.Mesh;
    ["Cingulate_gyrus_and_sulcus_(Middle_posterior_part)"]: THREE.Mesh;
    ["Cingulate_gyrus_and_sulcus_(Middle_posterior_part)_1"]: THREE.Mesh;
    ["Cingulate_gyrus_and_sulcus_(Posterior_dorsal_part)"]: THREE.Mesh;
    ["Cingulate_gyrus_and_sulcus_(Posterior_dorsal_part)_1"]: THREE.Mesh;
    ["Cingulate_gyrus_(Posteroventral_part*)"]: THREE.Mesh;
    ["Cingulate_gyrus_(Posteroventral_part*)_1"]: THREE.Mesh;
    White_matter_of_telencephalonr: THREE.Mesh;
    ["Lat_Fis-ant-Horizont"]: THREE.Mesh;
    ["Lat_Fis-ant-Horizont_1"]: THREE.Mesh;
    ["Lat_Fis-post"]: THREE.Mesh;
    ["Lat_Fis-post_1"]: THREE.Mesh;
    _Posterior_transverse_collateral_sulcus: THREE.Mesh;
    _Posterior_transverse_collateral_sulcus_1: THREE.Mesh;
    ["Sulcus_interm_prim-Jensen"]: THREE.Mesh;
    ["Sulcus_interm_prim-Jensen_1"]: THREE.Mesh;
    Wing_of_central_lobuler: THREE.Mesh;
    Tonsil_of_cerebellumr: THREE.Mesh;
    Superior_semilunar_lobuler: THREE.Mesh;
    Superior_cerebellar_peduncler: THREE.Mesh;
    Posterior_quadrangular_lobuler: THREE.Mesh;
    Peduncle_of_flocculusr: THREE.Mesh;
    Inferior_semilunar_lobuler: THREE.Mesh;
    Gracile_lobuler: THREE.Mesh;
    Flocculusr: THREE.Mesh;
    Biventral_lobuler: THREE.Mesh;
    Anterior_quadrangular_lobuler: THREE.Mesh;
    Tentorium_cerebellil: THREE.Mesh;
    Globus_pallidus_externall: THREE.Mesh;
    Globus_pallidus_externalr: THREE.Mesh;
    Globus_pallidus_internall: THREE.Mesh;
    Globus_pallidus_internalr: THREE.Mesh;
    Subthalamic_nucleusl: THREE.Mesh;
    Subthalamic_nucleusr: THREE.Mesh;
    Substantia_nigral: THREE.Mesh;
    Substantia_nigrar: THREE.Mesh;
    Nucleus_accumbensl: THREE.Mesh;
    Nucleus_accumbensr: THREE.Mesh;
    Pulvinarl: THREE.Mesh;
    Pulvinarr: THREE.Mesh;
    Anterior_nuclei_of_thalamusl: THREE.Mesh;
    Anterior_nuclei_of_thalamusr: THREE.Mesh;
    Mediodorsal_nucleusl: THREE.Mesh;
    Mediodorsal_nucleusr: THREE.Mesh;
    Ventral_laterodorsal_nucleusl: THREE.Mesh;
    Ventral_laterodorsal_nucleusr: THREE.Mesh;
    Intralaminar_and_lateral_posterior_nucleil: THREE.Mesh;
    Intralaminar_and_lateral_posterior_nucleir: THREE.Mesh;
    Ventral_anterior_nucleusl: THREE.Mesh;
    Ventral_anterior_nucleusr: THREE.Mesh;
    Ventral_lateroventral_nucleusl: THREE.Mesh;
    Ventral_lateroventral_nucleusr: THREE.Mesh;
    Lateral_nucleusl: THREE.Mesh;
    Lateral_nucleusr: THREE.Mesh;
    Basolateral_complexl: THREE.Mesh;
    Basolateral_complexr: THREE.Mesh;
    Central_nucleusl: THREE.Mesh;
    Central_nucleusr: THREE.Mesh;
    Corticomedial_groupl: THREE.Mesh;
    Corticomedial_groupr: THREE.Mesh;
    Preoptic_hypothalamusl: THREE.Mesh;
    Preoptic_hypothalamusr: THREE.Mesh;
    Anterior_hypothalamusl: THREE.Mesh;
    Anterior_hypothalamusr: THREE.Mesh;
    Tuberal_hypothalamusl: THREE.Mesh;
    Tuberal_hypothalamusr: THREE.Mesh;
    Lateral_hypothalamusl: THREE.Mesh;
    Lateral_hypothalamusr: THREE.Mesh;
    Posterior_hypothalamusl: THREE.Mesh;
    Posterior_hypothalamusr: THREE.Mesh;
    Adenohypophysis: THREE.Mesh;
    Neurohypophysis: THREE.Mesh;
    Pineal_gland: THREE.Mesh;
    ["Abducens_nerve_(VI)l"]: THREE.Mesh;
    ["Abducens_nerve_(VI)r"]: THREE.Mesh;
    ["Accessory_nerve_(XI)l"]: THREE.Mesh;
    ["Accessory_nerve_(XI)r"]: THREE.Mesh;
    Acoustic_radiationl: THREE.Mesh;
    Acoustic_radiationr: THREE.Mesh;
    Anterior_division_of_mandibular_nervel: THREE.Mesh;
    Anterior_division_of_mandibular_nerver: THREE.Mesh;
    Anterior_thalamic_radiationl: THREE.Mesh;
    Anterior_thalamic_radiationr: THREE.Mesh;
    Arcuate_fasciculusl: THREE.Mesh;
    Arcuate_fasciculusr: THREE.Mesh;
    Buccal_nervel: THREE.Mesh;
    Buccal_nerver: THREE.Mesh;
    Corticobulbar_tractl: THREE.Mesh;
    Corticobulbar_tractr: THREE.Mesh;
    ["Corticopontine_tract_(frontal)l"]: THREE.Mesh;
    ["Corticopontine_tract_(frontal)r"]: THREE.Mesh;
    ["Corticopontine_tract_(occipital)l"]: THREE.Mesh;
    ["Corticopontine_tract_(occipital)r"]: THREE.Mesh;
    ["Corticopontine_tract_(parietal)l"]: THREE.Mesh;
    ["Corticopontine_tract_(parietal)r"]: THREE.Mesh;
    Corticospinal_tractl: THREE.Mesh;
    Corticospinal_tractr: THREE.Mesh;
    ["Corticostriatal_tract_(anterior)l"]: THREE.Mesh;
    ["Corticostriatal_tract_(anterior)r"]: THREE.Mesh;
    ["Corticostriatal_tract_(posterior)l"]: THREE.Mesh;
    ["Corticostriatal_tract_(posterior)r"]: THREE.Mesh;
    ["Corticostriatal_tract_(superior)l"]: THREE.Mesh;
    ["Corticostriatal_tract_(superior)r"]: THREE.Mesh;
    Dentatorubrothalamic_tractl: THREE.Mesh;
    Dentatorubrothalamic_tractr: THREE.Mesh;
    ["Facial_nerve_(VII)l"]: THREE.Mesh;
    ["Facial_nerve_(VII)r"]: THREE.Mesh;
    Frontal_aslant_tractl: THREE.Mesh;
    Frontal_aslant_tractr: THREE.Mesh;
    ["Hypoglossal_nerve_(XII)l"]: THREE.Mesh;
    ["Hypoglossal_nerve_(XII)r"]: THREE.Mesh;
    Inferior_alveolar_nervel: THREE.Mesh;
    Inferior_alveolar_nerver: THREE.Mesh;
    Inferior_cerebellar_pedunclel: THREE.Mesh;
    Inferior_cerebellar_peduncler: THREE.Mesh;
    ["Inferior_fronto-occipital_fasciculusl"]: THREE.Mesh;
    ["Inferior_fronto-occipital_fasciculusr"]: THREE.Mesh;
    Inferior_longitudinal_fasciculusl: THREE.Mesh;
    Inferior_longitudinal_fasciculusr: THREE.Mesh;
    Lingual_nervel: THREE.Mesh;
    Lingual_nerver: THREE.Mesh;
    Maxillary_nervel: THREE.Mesh;
    Maxillary_nerver: THREE.Mesh;
    Medial_lemniscusl: THREE.Mesh;
    Medial_lemniscusr: THREE.Mesh;
    Meningeal_branch_of_maxillary_nervel: THREE.Mesh;
    Meningeal_branch_of_maxillary_nerver: THREE.Mesh;
    Mental_nervel: THREE.Mesh;
    Mental_nerver: THREE.Mesh;
    Middle_cerebellar_peduncle: THREE.Mesh;
    Middle_longitudinal_fasciculusl: THREE.Mesh;
    Middle_longitudinal_fasciculusr: THREE.Mesh;
    ["Oculomotor_nerve_(III)l"]: THREE.Mesh;
    ["Oculomotor_nerve_(III)r"]: THREE.Mesh;
    ["Olfactory_nerve_(I)l"]: THREE.Mesh;
    ["Olfactory_nerve_(I)r"]: THREE.Mesh;
    Ophthalmic_nervel: THREE.Mesh;
    Ophthalmic_nerver: THREE.Mesh;
    ["Optic_nerve_(II)l"]: THREE.Mesh;
    ["Optic_nerve_(II)r"]: THREE.Mesh;
    Optic_radiationl: THREE.Mesh;
    Optic_radiationr: THREE.Mesh;
    Posterior_division_of_mandibular_nervel: THREE.Mesh;
    Posterior_division_of_mandibular_nerver: THREE.Mesh;
    Posterior_thalamic_radiationl: THREE.Mesh;
    Posterior_thalamic_radiationr: THREE.Mesh;
    Reticulospinal_tractl: THREE.Mesh;
    Reticulospinal_tractr: THREE.Mesh;
    Superior_cerebellar_peduncle: THREE.Mesh;
    Superior_longitudinal_fasciculus_Il: THREE.Mesh;
    Superior_longitudinal_fasciculus_Ir: THREE.Mesh;
    Superior_longitudinal_fasciculus_IIl: THREE.Mesh;
    Superior_longitudinal_fasciculus_IIr: THREE.Mesh;
    Superior_longitudinal_fasciculus_IIIl: THREE.Mesh;
    Superior_longitudinal_fasciculus_IIIr: THREE.Mesh;
    Superior_thalamic_radiationl: THREE.Mesh;
    Superior_thalamic_radiationr: THREE.Mesh;
    ["Trigeminal_nerve_(V)l"]: THREE.Mesh;
    ["Trigeminal_nerve_(V)r"]: THREE.Mesh;
    ["Trochlear_nerve_(IV)l"]: THREE.Mesh;
    ["Trochlear_nerve_(IV)r"]: THREE.Mesh;
    Uncinate_fasciculusl: THREE.Mesh;
    Uncinate_fasciculusr: THREE.Mesh;
    ["Vagus_nerve_(X)l"]: THREE.Mesh;
    ["Vagus_nerve_(X)r"]: THREE.Mesh;
    Vestibular_nervel: THREE.Mesh;
    Vestibular_nerver: THREE.Mesh;
  };
  materials: {
    Artery: THREE.MeshStandardMaterial;
    Cartilage: THREE.MeshStandardMaterial;
    ["Temporal lobe"]: THREE.MeshStandardMaterial;
    ["Brain-Inner"]: THREE.MeshStandardMaterial;
    Brain: THREE.MeshStandardMaterial;
    Nucleus: THREE.MeshStandardMaterial;
    ["White matter"]: THREE.MeshStandardMaterial;
    Nerve: THREE.MeshStandardMaterial;
    LCR: THREE.MeshStandardMaterial;
    ["Nucleus (efferent fibers)"]: THREE.MeshStandardMaterial;
    ["Nucleus (afferent fibers)"]: THREE.MeshStandardMaterial;
    Cerebellum: THREE.MeshStandardMaterial;
    ["Bone-4"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function BrainModel({ customMaterial, ...props }: any) {
  const { nodes, materials } = useGLTF("/brain.glb") as any;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Anterior_communicating_artery.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Basilar_venous_plexus.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Cavernous_sinusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Cavernous_sinusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_cerebral_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_cerebral_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_inferior_cerebellar_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_inferior_cerebellar_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_intercavernous_sinus.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_spinal_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_spinal_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Basilar_artery.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Callosomarginal_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Callosomarginal_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Distal_lateral_striate_branchesl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Distal_lateral_striate_branchesr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Frontal_branches_of_callosomarginal_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Frontal_branches_of_callosomarginal_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Inferior_petrosal_sinusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Inferior_petrosal_sinusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Inferior_sagittal_sinus.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={
          nodes["Insular_branches_of_middle_cerebral_artery_(M2)r"].geometry
        }
        material={customMaterial}
      />
      <mesh
        geometry={
          nodes["Insular_branches_of_middle_cerebral_artery_(M2-segment)l"]
            .geometry
        }
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Internal_carotid_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Internal_carotid_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Lateral_pontine_branches_of_basilar_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Lateral_pontine_branches_of_basilar_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Medial_pontine_branches_of_basilar_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Medial_pontine_branches_of_basilar_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Middle_cerebral_artery_(M1-segment)l"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Middle_cerebral_artery_(M1-segment)r"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Middle_cerebral_artery_(M3_segment)l"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Middle_cerebral_artery_(M3-segment)r"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Occipital_sinus.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Ophthalmic_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Ophthalmic_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={
          nodes.Orbitofrontal_branches_of_anterior_cerebral_arteryl.geometry
        }
        material={customMaterial}
      />
      <mesh
        geometry={
          nodes.Orbitofrontal_branches_of_anterior_cerebral_arteryr.geometry
        }
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Parietal_branches_of_middle_cerebral_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Parietal_branches_of_middle_cerebral_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Pericallosal_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Pericallosal_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_cerebral_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_cerebral_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_communicating_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_communicating_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_inferior_cerebellar_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_inferior_cerebellar_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_intercavernous_sinus.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Proximal_lateral_striate_branchesl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Proximal_lateral_striate_branchesr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Sigmoid_sinusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Sigmoid_sinusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Straight_sinus.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_cerebellar_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_cerebellar_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_petrosal_sinusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_petrosal_sinusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_sagittal_sinus.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Temporal_branches_of_middle_cerebral_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Temporal_branches_of_middle_cerebral_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Transverse_sinusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Transverse_sinusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Vertebral_arteryl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Vertebral_arteryr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Tentorium_cerebellir.geometry}
        material={customMaterial}
      />
      <mesh geometry={nodes.Falx_cerebri.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Choroid_plexusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Choroid_plexusl.geometry}
        material={customMaterial}
      />
      <mesh geometry={nodes.Hippocampusr.geometry} material={customMaterial} />
      <mesh geometry={nodes.Hippocampusl.geometry} material={customMaterial} />
      <mesh geometry={nodes.Septal_nuclei.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Caudate_nucleusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Caudate_nucleusl.geometry}
        material={customMaterial}
      />
      <mesh geometry={nodes.Putamenr.geometry} material={customMaterial} />
      <mesh geometry={nodes.Putamenl.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Corpus_callosum.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Anterior_commissure.geometry}
        material={materials["White matter"]}
      />
      <mesh
        geometry={nodes.Hippocampal_commissure.geometry}
        material={materials["White matter"]}
      />
      <mesh
        geometry={nodes.Fornixr.geometry}
        material={materials["White matter"]}
      />
      <mesh
        geometry={nodes.Fornixl.geometry}
        material={materials["White matter"]}
      />
      <mesh
        geometry={nodes.Stria_terminalisr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Stria_terminalisl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.White_matter_of_telencephalonl.geometry}
        material={materials["White matter"]}
      />
      <mesh
        geometry={nodes.Lateral_ventricler.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Lateral_ventriclel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Septum_pellucidum.geometry}
        material={materials["White matter"]}
      />
      <mesh geometry={nodes.Habenula.geometry} material={customMaterial} />
      <mesh geometry={nodes.Optic_tractr.geometry} material={customMaterial} />
      <mesh geometry={nodes.Optic_tractl.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Stria_medullaris_thalamir.geometry}
        material={materials["White matter"]}
      />
      <mesh
        geometry={nodes.Stria_medullaris_thalamil.geometry}
        material={materials["White matter"]}
      />
      <mesh
        geometry={nodes.Posterior_commissure.geometry}
        material={materials["White matter"]}
      />
      <mesh
        geometry={nodes.Third_ventricle.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Lateral_geniculate_bodyr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Medial_geniculate_bodyr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Mamillary_bodyl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Mamillary_bodyr.geometry}
        material={customMaterial}
      />
      <mesh geometry={nodes.Optic_chiasmr.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Lateral_geniculate_bodyl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Medial_geniculate_bodyl.geometry}
        material={customMaterial}
      />
      <mesh geometry={nodes.Optic_chiasml.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Base_of_peduncler.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Base_of_pedunclel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Nucleus_of_oculomotor_nervel.geometry}
        material={materials["Nucleus (efferent fibers)"]}
      />
      <mesh
        geometry={nodes.Nucleus_of_oculomotor_nerver.geometry}
        material={materials["Nucleus (efferent fibers)"]}
      />
      <mesh
        geometry={nodes.Accessory_nucleus_of_oculomotor_nerver.geometry}
        material={materials["Nucleus (efferent fibers)"]}
      />
      <mesh
        geometry={nodes.Accessory_nucleus_of_oculomotor_nervel.geometry}
        material={materials["Nucleus (efferent fibers)"]}
      />
      <mesh geometry={nodes.Red_nucleusl.geometry} material={customMaterial} />
      <mesh geometry={nodes.Red_nucleusr.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Aqueduct_of_midbrain.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_colliculusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_colliculusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Inferior_colliculusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Inferior_colliculusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Midbrainr.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Interpeduncular_fossal.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Interpeduncular_fossar.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Midbrainl.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Vestibular_nucleil.geometry}
        material={materials["Nucleus (afferent fibers)"]}
      />
      <mesh
        geometry={nodes.Vestibular_nucleir.geometry}
        material={materials["Nucleus (afferent fibers)"]}
      />
      <mesh
        geometry={nodes.Nucleus_of_abducens_nervel.geometry}
        material={materials["Nucleus (efferent fibers)"]}
      />
      <mesh
        geometry={nodes.Nucleus_of_abducens_nerver.geometry}
        material={materials["Nucleus (efferent fibers)"]}
      />
      <mesh
        geometry={nodes.Motor_nucleus_of_facial_nervel.geometry}
        material={materials["Nucleus (efferent fibers)"]}
      />
      <mesh
        geometry={nodes.Motor_nucleus_of_facial_nerver.geometry}
        material={materials["Nucleus (efferent fibers)"]}
      />
      <mesh
        geometry={nodes.Superior_salivatory_nucleusl.geometry}
        material={materials["Nucleus (efferent fibers)"]}
      />
      <mesh
        geometry={nodes.Superior_salivatory_nucleusr.geometry}
        material={materials["Nucleus (efferent fibers)"]}
      />
      <mesh geometry={nodes.Ponsr.geometry} material={customMaterial} />
      <mesh geometry={nodes.Ponsl.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Fourth_ventricle.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Medulla_oblongatal.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Pyramid_of_medulla_oblongatal.geometry}
        material={customMaterial}
      />
      <mesh geometry={nodes.Oliver.geometry} material={customMaterial} />
      <mesh geometry={nodes.Olivel.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Pyramid_of_medulla_oblongatar.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Sensory_root_of_trigeminal_nerver.geometry}
        material={materials["Nucleus (afferent fibers)"]}
      />
      <mesh
        geometry={nodes.Sensory_root_of_trigeminal_nervel.geometry}
        material={materials["Nucleus (afferent fibers)"]}
      />
      <mesh
        geometry={nodes.Motor_root_of_trigeminal_nervel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Motor_root_of_trigeminal_nerver.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Wing_of_central_lobulel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Uvula_of_vermis.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Tuber_of_vermis.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Tonsil_of_cerebelluml.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_semilunar_lobulel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_cerebellar_pedunclel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Pyramis_of_vermis.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_quadrangular_lobulel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Peduncle_of_flocculusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Nodule_of_vermis.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Lingula_of_cerebellum.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Inferior_semilunar_lobulel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Gracile_lobulel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Folium_of_vermis.geometry}
        material={customMaterial}
      />
      <mesh geometry={nodes.Flocculusl.geometry} material={customMaterial} />
      <mesh geometry={nodes.Declive.geometry} material={customMaterial} />
      <mesh geometry={nodes.Culmen.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Central_lobule.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Biventral_lobulel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_quadrangular_lobulel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.White_matter_of_telencephalonr.geometry}
        material={materials["White matter"]}
      />
      <mesh
        geometry={nodes.Wing_of_central_lobuler.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Tonsil_of_cerebellumr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_semilunar_lobuler.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_cerebellar_peduncler.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_quadrangular_lobuler.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Peduncle_of_flocculusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Inferior_semilunar_lobuler.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Gracile_lobuler.geometry}
        material={customMaterial}
      />
      <mesh geometry={nodes.Flocculusr.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Biventral_lobuler.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_quadrangular_lobuler.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Tentorium_cerebellil.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Globus_pallidus_externall.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Globus_pallidus_externalr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Globus_pallidus_internall.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Globus_pallidus_internalr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Subthalamic_nucleusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Subthalamic_nucleusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Substantia_nigral.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Substantia_nigrar.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Nucleus_accumbensl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Nucleus_accumbensr.geometry}
        material={customMaterial}
      />
      <mesh geometry={nodes.Pulvinarl.geometry} material={customMaterial} />
      <mesh geometry={nodes.Pulvinarr.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Anterior_nuclei_of_thalamusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_nuclei_of_thalamusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Mediodorsal_nucleusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Mediodorsal_nucleusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Ventral_laterodorsal_nucleusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Ventral_laterodorsal_nucleusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Intralaminar_and_lateral_posterior_nucleil.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Intralaminar_and_lateral_posterior_nucleir.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Ventral_anterior_nucleusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Ventral_anterior_nucleusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Ventral_lateroventral_nucleusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Ventral_lateroventral_nucleusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Lateral_nucleusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Lateral_nucleusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Basolateral_complexl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Basolateral_complexr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Central_nucleusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Central_nucleusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Corticomedial_groupl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Corticomedial_groupr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Preoptic_hypothalamusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Preoptic_hypothalamusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_hypothalamusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_hypothalamusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Tuberal_hypothalamusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Tuberal_hypothalamusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Lateral_hypothalamusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Lateral_hypothalamusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_hypothalamusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_hypothalamusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Adenohypophysis.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Neurohypophysis.geometry}
        material={customMaterial}
      />
      <mesh geometry={nodes.Pineal_gland.geometry} material={customMaterial} />
      <mesh
        geometry={nodes["Abducens_nerve_(VI)l"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Abducens_nerve_(VI)r"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Accessory_nerve_(XI)l"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Accessory_nerve_(XI)r"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Acoustic_radiationl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Acoustic_radiationr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_division_of_mandibular_nervel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_division_of_mandibular_nerver.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_thalamic_radiationl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Anterior_thalamic_radiationr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Arcuate_fasciculusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Arcuate_fasciculusr.geometry}
        material={customMaterial}
      />
      <mesh geometry={nodes.Buccal_nervel.geometry} material={customMaterial} />
      <mesh geometry={nodes.Buccal_nerver.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Corticobulbar_tractl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Corticobulbar_tractr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Corticopontine_tract_(frontal)l"].geometry}
        material={nodes["Corticopontine_tract_(frontal)l"].material}
      />
      <mesh
        geometry={nodes["Corticopontine_tract_(frontal)r"].geometry}
        material={nodes["Corticopontine_tract_(frontal)r"].material}
      />
      <mesh
        geometry={nodes["Corticopontine_tract_(occipital)l"].geometry}
        material={nodes["Corticopontine_tract_(occipital)l"].material}
      />
      <mesh
        geometry={nodes["Corticopontine_tract_(occipital)r"].geometry}
        material={nodes["Corticopontine_tract_(occipital)r"].material}
      />
      <mesh
        geometry={nodes["Corticopontine_tract_(parietal)l"].geometry}
        material={nodes["Corticopontine_tract_(parietal)l"].material}
      />
      <mesh
        geometry={nodes["Corticopontine_tract_(parietal)r"].geometry}
        material={nodes["Corticopontine_tract_(parietal)r"].material}
      />
      <mesh
        geometry={nodes.Corticospinal_tractl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Corticospinal_tractr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Corticostriatal_tract_(anterior)l"].geometry}
        material={nodes["Corticostriatal_tract_(anterior)l"].material}
      />
      <mesh
        geometry={nodes["Corticostriatal_tract_(anterior)r"].geometry}
        material={nodes["Corticostriatal_tract_(anterior)r"].material}
      />
      <mesh
        geometry={nodes["Corticostriatal_tract_(posterior)l"].geometry}
        material={nodes["Corticostriatal_tract_(posterior)l"].material}
      />
      <mesh
        geometry={nodes["Corticostriatal_tract_(posterior)r"].geometry}
        material={nodes["Corticostriatal_tract_(posterior)r"].material}
      />
      <mesh
        geometry={nodes["Corticostriatal_tract_(superior)l"].geometry}
        material={nodes["Corticostriatal_tract_(superior)l"].material}
      />
      <mesh
        geometry={nodes["Corticostriatal_tract_(superior)r"].geometry}
        material={nodes["Corticostriatal_tract_(superior)r"].material}
      />
      <mesh
        geometry={nodes.Dentatorubrothalamic_tractl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Dentatorubrothalamic_tractr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Facial_nerve_(VII)l"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Facial_nerve_(VII)r"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Frontal_aslant_tractl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Frontal_aslant_tractr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Hypoglossal_nerve_(XII)l"].geometry}
        material={materials["Bone-4"]}
      />
      <mesh
        geometry={nodes["Hypoglossal_nerve_(XII)r"].geometry}
        material={materials["Bone-4"]}
      />
      <mesh
        geometry={nodes.Inferior_alveolar_nervel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Inferior_alveolar_nerver.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Inferior_cerebellar_pedunclel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Inferior_cerebellar_peduncler.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Inferior_fronto-occipital_fasciculusl"].geometry}
        material={nodes["Inferior_fronto-occipital_fasciculusl"].material}
      />
      <mesh
        geometry={nodes["Inferior_fronto-occipital_fasciculusr"].geometry}
        material={nodes["Inferior_fronto-occipital_fasciculusr"].material}
      />
      <mesh
        geometry={nodes.Inferior_longitudinal_fasciculusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Inferior_longitudinal_fasciculusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Lingual_nervel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Lingual_nerver.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Maxillary_nervel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Maxillary_nerver.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Medial_lemniscusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Medial_lemniscusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Meningeal_branch_of_maxillary_nervel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Meningeal_branch_of_maxillary_nerver.geometry}
        material={customMaterial}
      />
      <mesh geometry={nodes.Mental_nervel.geometry} material={customMaterial} />
      <mesh geometry={nodes.Mental_nerver.geometry} material={customMaterial} />
      <mesh
        geometry={nodes.Middle_cerebellar_peduncle.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Middle_longitudinal_fasciculusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Middle_longitudinal_fasciculusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Oculomotor_nerve_(III)l"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Oculomotor_nerve_(III)r"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Olfactory_nerve_(I)l"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Olfactory_nerve_(I)r"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Ophthalmic_nervel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Ophthalmic_nerver.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Optic_nerve_(II)l"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Optic_nerve_(II)r"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Optic_radiationl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Optic_radiationr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_division_of_mandibular_nervel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_division_of_mandibular_nerver.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_thalamic_radiationl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Posterior_thalamic_radiationr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Reticulospinal_tractl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Reticulospinal_tractr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_cerebellar_peduncle.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_longitudinal_fasciculus_Il.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_longitudinal_fasciculus_Ir.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_longitudinal_fasciculus_IIl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_longitudinal_fasciculus_IIr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_longitudinal_fasciculus_IIIl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_longitudinal_fasciculus_IIIr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_thalamic_radiationl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Superior_thalamic_radiationr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Trigeminal_nerve_(V)l"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Trigeminal_nerve_(V)r"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Trochlear_nerve_(IV)l"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Trochlear_nerve_(IV)r"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Uncinate_fasciculusl.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Uncinate_fasciculusr.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Vagus_nerve_(X)l"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes["Vagus_nerve_(X)r"].geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Vestibular_nervel.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Vestibular_nerver.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Temporal_pole001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Temporal_pole001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Occipital_pole001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Occipital_pole001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Central_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Central_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Parieto-occipital_sulcus001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Parieto-occipital_sulcus001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Subparietal_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Subparietal_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Cingulate_sulcus_(Marginal_part*)001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Cingulate_sulcus_(Marginal_part*)001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Circular_sulcus_of_insula001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Circular_sulcus_of_insula001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Collateral_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Collateral_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Anterior_occipital_sulcus*001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Anterior_occipital_sulcus*001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Opercular_part_of_inferior_frontal_gyrus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Opercular_part_of_inferior_frontal_gyrus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Orbital_part_of__inferior_frontal_gyrus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Orbital_part_of__inferior_frontal_gyrus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Triangular_part_of_inferior_frontal_gyrus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Triangular_part_of_inferior_frontal_gyrus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Orbital_gyri_(Frontomarginal_gyrus_and_sulcus*)001"].geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Orbital_gyri_(Frontomarginal_gyrus_and_sulcus*)001_1"].geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Paracentral_gyrus_and_sulcus*001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Paracentral_gyrus_and_sulcus*001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Transverse_frontopolar_gyrus_and_sulcus*001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Transverse_frontopolar_gyrus_and_sulcus*001_1"].geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Straight_gyrus_(Gyrus_rectus)001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Straight_gyrus_(Gyrus_rectus)001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Lat_Fis-ant-Vertical001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Lat_Fis-ant-Vertical001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Inferior_frontal_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Inferior_frontal_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Middle_frontal_gyrus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Middle_frontal_gyrus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Orbital_gyri001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Orbital_gyri001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Precentral_gyrus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Precentral_gyrus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Superior_frontal_gyrus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Superior_frontal_gyrus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Superior_frontal_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Superior_frontal_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Paracentral_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Paracentral_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Orbital_sulci_(H-shaped_orbital_sulci*)001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Orbital_sulci_(H-shaped_orbital_sulci*)001_1"].geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Orbital_sulci_(Lateral_Orbital_sulcus*)001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Orbital_sulci_(Lateral_Orbital_sulcus*)001_1"].geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Olfactory_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Olfactory_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Precentral_sulcus_(inferior_part)*001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Precentral_sulcus_(inferior_part)*001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Precentral_sulcus_(Superior_part)*001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Precentral_sulcus_(Superior_part)*001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Angular_gyrus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Angular_gyrus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Supramarginal_gyrus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Supramarginal_gyrus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Postcentral_gyrus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Postcentral_gyrus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Postcentral_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Postcentral_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Precuneus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Precuneus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Superior_parietal_lobule001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Superior_parietal_lobule001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Intraparietal_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Intraparietal_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Inferior_occipital_gyrus_and_sulcus*001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Inferior_occipital_gyrus_and_sulcus*001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Lingual_gyrus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Lingual_gyrus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Lateral_occipital_gyrus_(Middle_occipital_gyrus*)001"].geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Lateral_occipital_gyrus_(Middle_occipital_gyrus*)001_1"]
            .geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Calcarine_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Calcarine_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Cuneus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Cuneus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Superior_occipital_gyri001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Superior_occipital_gyri001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Lunate_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Lunate_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Transverse_occipital_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Transverse_occipital_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Transverse_temporal_gyri001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Transverse_temporal_gyri001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Temporal_plane001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Temporal_plane001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Superior_temporal_gyrus_(Lateral_part)001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Superior_temporal_gyrus_(Lateral_part)001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Lateral_occipitotemporal_gyrus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Lateral_occipitotemporal_gyrus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Medial_occipitotemporal_gyrus_(Parahippocampal*)001"].geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Medial_occipitotemporal_gyrus_(Parahippocampal*)001_1"]
            .geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Inferior_temporal_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Inferior_temporal_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Inferior_temporal_gyrus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Inferior_temporal_gyrus001_1.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Middle_temporal_gyrus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Middle_temporal_gyrus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Superior_temporal_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Superior_temporal_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Occipitotemporal_sulcus_(Lateral_part*)001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Occipitotemporal_sulcus_(Lateral_part*)001_1"].geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Insula_(Subcentral_gyrus_and_ant_and_post_sulci*)001"].geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Insula_(Subcentral_gyrus_and_ant_and_post_sulci*)001_1"]
            .geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Cingulate_gyrus_and_sulcus_(Middle_anterior_part)001"].geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Cingulate_gyrus_and_sulcus_(Middle_anterior_part)001_1"]
            .geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Cingulate_gyrus_and_sulcus_(Middle_posterior_part)001"]
            .geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Cingulate_gyrus_and_sulcus_(Middle_posterior_part)001_1"]
            .geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Cingulate_gyrus_and_sulcus_(Posterior_dorsal_part)001"]
            .geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Cingulate_gyrus_and_sulcus_(Posterior_dorsal_part)001_1"]
            .geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Cingulate_gyrus_(Posteroventral_part*)001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Cingulate_gyrus_(Posteroventral_part*)001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Lat_Fis-ant-Horizont001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Lat_Fis-ant-Horizont001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Lat_Fis-post001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Lat_Fis-post001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes._Posterior_transverse_collateral_sulcus001.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes._Posterior_transverse_collateral_sulcus001_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Sulcus_interm_prim-Jensen001"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Sulcus_interm_prim-Jensen001_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Temporal_pole.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Temporal_pole_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Occipital_pole.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Occipital_pole_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Central_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Central_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Parieto-occipital_sulcus"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Parieto-occipital_sulcus_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Subparietal_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Subparietal_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Cingulate_sulcus_(Marginal_part*)"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Cingulate_sulcus_(Marginal_part*)_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Circular_sulcus_of_insula.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Circular_sulcus_of_insula_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Collateral_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Collateral_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Anterior_occipital_sulcus*"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Anterior_occipital_sulcus*_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Opercular_part_of_inferior_frontal_gyrus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Opercular_part_of_inferior_frontal_gyrus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Orbital_part_of__inferior_frontal_gyrus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Orbital_part_of__inferior_frontal_gyrus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Triangular_part_of_inferior_frontal_gyrus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Triangular_part_of_inferior_frontal_gyrus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Orbital_gyri_(Frontomarginal_gyrus_and_sulcus*)"].geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Orbital_gyri_(Frontomarginal_gyrus_and_sulcus*)_1"].geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Paracentral_gyrus_and_sulcus*"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Paracentral_gyrus_and_sulcus*_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Transverse_frontopolar_gyrus_and_sulcus*"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Transverse_frontopolar_gyrus_and_sulcus*_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Straight_gyrus_(Gyrus_rectus)"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Straight_gyrus_(Gyrus_rectus)_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Lat_Fis-ant-Vertical"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Lat_Fis-ant-Vertical_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Inferior_frontal_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Inferior_frontal_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Middle_frontal_gyrus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Middle_frontal_gyrus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Orbital_gyri.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Orbital_gyri_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Precentral_gyrus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Precentral_gyrus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Superior_frontal_gyrus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Superior_frontal_gyrus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Superior_frontal_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Superior_frontal_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Paracentral_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Paracentral_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Orbital_sulci_(H-shaped_orbital_sulci*)"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Orbital_sulci_(H-shaped_orbital_sulci*)_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Orbital_sulci_(Lateral_Orbital_sulcus*)"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Orbital_sulci_(Lateral_Orbital_sulcus*)_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Olfactory_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Olfactory_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Precentral_sulcus_(inferior_part)*"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Precentral_sulcus_(inferior_part)*_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Precentral_sulcus_(Superior_part)*"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Precentral_sulcus_(Superior_part)*_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Angular_gyrus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Angular_gyrus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Supramarginal_gyrus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Supramarginal_gyrus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Postcentral_gyrus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Postcentral_gyrus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Postcentral_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Postcentral_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Precuneus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Precuneus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Superior_parietal_lobule.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Superior_parietal_lobule_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Intraparietal_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Intraparietal_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Inferior_occipital_gyrus_and_sulcus*"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Inferior_occipital_gyrus_and_sulcus*_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Lingual_gyrus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Lingual_gyrus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Lateral_occipital_gyrus_(Middle_occipital_gyrus*)"].geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Lateral_occipital_gyrus_(Middle_occipital_gyrus*)_1"].geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Calcarine_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Calcarine_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Cuneus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Cuneus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Superior_occipital_gyri.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Superior_occipital_gyri_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Lunate_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Lunate_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Transverse_occipital_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Transverse_occipital_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Transverse_temporal_gyri.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Transverse_temporal_gyri_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Temporal_plane.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Temporal_plane_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Superior_temporal_gyrus_(Lateral_part)"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Superior_temporal_gyrus_(Lateral_part)_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Lateral_occipitotemporal_gyrus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Lateral_occipitotemporal_gyrus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Medial_occipitotemporal_gyrus_(Parahippocampal*)"].geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Medial_occipitotemporal_gyrus_(Parahippocampal*)_1"].geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Inferior_temporal_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Inferior_temporal_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Inferior_temporal_gyrus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Inferior_temporal_gyrus_1.geometry}
        material={customMaterial}
      />
      <mesh
        geometry={nodes.Middle_temporal_gyrus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Middle_temporal_gyrus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes.Superior_temporal_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes.Superior_temporal_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Occipitotemporal_sulcus_(Lateral_part*)"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Occipitotemporal_sulcus_(Lateral_part*)_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Insula_(Subcentral_gyrus_and_ant_and_post_sulci*)"].geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Insula_(Subcentral_gyrus_and_ant_and_post_sulci*)_1"].geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Cingulate_gyrus_and_sulcus_(Middle_anterior_part)"].geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Cingulate_gyrus_and_sulcus_(Middle_anterior_part)_1"].geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Cingulate_gyrus_and_sulcus_(Middle_posterior_part)"].geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Cingulate_gyrus_and_sulcus_(Middle_posterior_part)_1"].geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={
          nodes["Cingulate_gyrus_and_sulcus_(Posterior_dorsal_part)"].geometry
        }
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={
          nodes["Cingulate_gyrus_and_sulcus_(Posterior_dorsal_part)_1"].geometry
        }
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Cingulate_gyrus_(Posteroventral_part*)"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Cingulate_gyrus_(Posteroventral_part*)_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Lat_Fis-ant-Horizont"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Lat_Fis-ant-Horizont_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Lat_Fis-post"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Lat_Fis-post_1"].geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes._Posterior_transverse_collateral_sulcus.geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes._Posterior_transverse_collateral_sulcus_1.geometry}
        material={materials["Brain-Inner"]}
      />
      <mesh
        geometry={nodes["Sulcus_interm_prim-Jensen"].geometry}
        material={materials["Temporal lobe"]}
      />
      <mesh
        geometry={nodes["Sulcus_interm_prim-Jensen_1"].geometry}
        material={materials["Brain-Inner"]}
      />
    </group>
  );
}

useGLTF.preload("/brain.glb");
