"""Data partitioning for simulated federated learning hospitals.

Task 17 — Partition data across simulated hospitals.

Partitions the sliced dataset into non-IID datasets for each simulated hospital,
ensuring strict patient isolation (no patient leakage across hospitals).
"""

from __future__ import annotations

import logging
from pathlib import Path

import numpy as np
import pandas as pd

logger = logging.getLogger(__name__)


def partition_by_patient(
    manifest_path: Path | str,
    num_clients: int = 3,
    alpha: float = 0.5,
    seed: int = 42,
    output_dir: Path | str | None = None,
) -> dict[int, pd.DataFrame]:
    """Partition the dataset into non-IID subsets by patient.

    Groups slices by `patient_id` so that all slices from one patient go to
    a single hospital client. Uses a Dirichlet distribution over the patient's
    majority class to simulate non-IID data distribution.

    Parameters
    ----------
    manifest_path : Path | str
        Path to the `manifest.csv` generated by `slicer.py`.
    num_clients : int
        Number of simulated hospitals to divide the data among.
    alpha : float
        Concentration parameter for the Dirichlet distribution. Smaller values
        (e.g., 0.1) mean higher data imbalance (strong non-IID).
    seed : int
        Random seed for reproducibility.
    output_dir : Path | str | None
        If provided, writes a summary CSV and individual partition CSVs here.

    Returns
    -------
    Dict[int, pd.DataFrame]
        A dictionary mapping client index (0 to num_clients-1) to its assigned
        slice manifest DataFrame.
    """
    rng = np.random.default_rng(seed)

    df = pd.read_csv(manifest_path)

    # 1. Group by patient and find their predominant label
    # Here we just use the sum of has_tumor to determine the patient "class".
    # Since our slices are tumor/no-tumor, a patient with any tumor slices
    # can be considered a "tumor patient" for distribution purposes.
    patient_stats = (
        df.groupby("patient_id")
        .agg(total_slices=("slice_idx", "count"), tumor_slices=("has_tumor", "sum"))
        .reset_index()
    )

    # Classify patient: 1 if they have tumor slices, 0 otherwise.
    # If the dataset was extracted with TUMOR_ONLY strategy, all might be 1.
    patient_stats["patient_class"] = (patient_stats["tumor_slices"] > 0).astype(int)

    unique_classes = patient_stats["patient_class"].unique()

    # 2. Dirichlet partitioning per class
    # For each class, draw a distribution over clients
    client_patient_ids: dict[int, list[str]] = {i: [] for i in range(num_clients)}

    for c in unique_classes:
        class_patients = patient_stats[patient_stats["patient_class"] == c]["patient_id"].values
        rng.shuffle(class_patients)

        # Proportions for each client for this class
        proportions = rng.dirichlet(np.repeat(alpha, num_clients))
        # Ensure it sums to 1 cleanly and handle rounding
        proportions = proportions / proportions.sum()

        # Allocate patients based on proportions
        splits = (np.cumsum(proportions) * len(class_patients)).astype(int)
        splits[-1] = len(class_patients)  # ensure all are allocated

        prev_split = 0
        for client_idx, split_idx in enumerate(splits):
            assigned = class_patients[prev_split:split_idx]
            client_patient_ids[client_idx].extend(assigned)
            prev_split = split_idx

    # 3. Build actual slice DataFrames for each client
    client_dfs = {}
    for client_idx, p_ids in client_patient_ids.items():
        client_df = df[df["patient_id"].isin(p_ids)].copy()
        client_dfs[client_idx] = client_df

    # 4. Generate summaries
    summaries = []
    for client_idx, cdf in client_dfs.items():
        total = len(cdf)
        tumor = cdf["has_tumor"].sum()
        no_tumor = total - tumor
        unique_patients = cdf["patient_id"].nunique()
        summaries.append(
            {
                "Hospital": f"Client {client_idx}",
                "Total Slices": total,
                "Tumor Slices": tumor,
                "No-Tumor Slices": no_tumor,
                "Unique Patients": unique_patients,
            }
        )

    summary_df = pd.DataFrame(summaries)
    logger.info("Partitioning Summary:\n%s", summary_df.to_string(index=False))

    if output_dir:
        out_path = Path(output_dir)
        out_path.mkdir(parents=True, exist_ok=True)
        summary_df.to_csv(out_path / "partition_summary.csv", index=False)
        for client_idx, cdf in client_dfs.items():
            cdf.to_csv(out_path / f"client_{client_idx}_manifest.csv", index=False)

    return client_dfs
